### ISSUE TITLE
Error compiling Magento 2.4.3

### ISSUE THREAD

**Issue by jasuten** [productreview/productreview-for-magento2#1]
We are getting the following error with the extension when running bin/magento setup:di:compile:

`Fatal error: Class Productreview\Reviews\Block\ProductReviewCodeSnippets\Interceptor may not inherit from final class (Productreview\Reviews\Block\ProductReviewCodeSnippets) in /opt/atlassian/pipelines/agent/build/generated/code/Productreview/Reviews/Block/ProductReviewCodeSnippets/Interceptor.php on line 7`

**Comment by grifx** [comment]
Thanks for reporting this bug. I removed the usage of final classes to allow Magento2 to proxy / extend classes.
I'm gonna do some testing during the week specifically on `Magento v2.4.3` using `productreview-for-magento2 v1.0.4`.

Don't forget to update your composer so you are using the latest version.

Cheers,
